version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend_collector:
    build: ./backend
    container_name: backend_collector
    restart: unless-stopped
    env_file:
      - ./.env
    command: node collector.js
    depends_on:
      - mongo

  backend_api:
    build: ./backend
    container_name: backend_api
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - ./.env
    command: node server.js
    depends_on:
      - mongo

  # Jaeger - Distributed Tracing UI
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # HTTP collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
    depends_on:
      - jaeger
    restart: unless-stopped

  # React Frontend
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend_api
    restart: unless-stopped

volumes:
  mongo-data:
